services:
  online-judge:
    image: nhathien/ojus-backend:latest
    container_name: ojus-container
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./codeFiles:/app/codeFiles
    privileged: true
    depends_on:
      - gcc
      - py
      - js
      - java