services:
  online-judge:
    image: nhathien/ojus-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./codeFiles:/app/codeFiles
    privileged: true
    depends_on:
      - gcc
      - py
      - js
      - java



#services:
#  mysql:
#    image: mysql:8
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 123
#    ports:
#      - "3307:3306"
#    volumes:
#      - ./mysql:/var/lib/mysql
#      - ./init.sql:/code-executor-entrypoint-initdb.d/init.sql
#
#  mysql_test:
#    image: mysql:8
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 123
#    ports:
#      - "3308:3306"
#    volumes:
#      - ./mysql_test:/var/lib/mysql
#      - ./init_test.sql:/docker-entrypoint-initdb.d/init_test.sql