# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push: 
    branches:
      - "**"
  pull_request: 
    branches:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          # The MySQL docker container requires these environment variables to be set
          # so we can create and migrate the test database.
          # See: https://hub.docker.com/_/mysql
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: 123
        ports:
          # Opens port 3306 on service container and host
          # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
          - 3308:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - run: npm ci
      working-directory: ./backend

    - name: Set up environment
      run: |
        touch ./backend/.env
        touch ./backend/.env.test
        touch ./backend/services/code-executor/codeFiles
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> ./backend/.env
        echo DATABASE_URL=${{ secrets.DATABASE_URL_TEST }} >> ./backend/.env.test
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> ./backend/.env
    - run: npm run build --if-present
      working-directory: ./backend
    - run: npm test
      working-directory: ./backend
